[package]
name = "adventofcode-2020"
version = "0.1.0"
authors = ["Emiliano Claria <emiliano.claria@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
text_io = "0.1.8"
itertools = "0.8.2"